In [ ]:
import pandas as pd
from pathlib import Path
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
csv_path = Path("Reviews.csv")
if not csv_path.exists():
    csv_path = Path("lab1/Reviews.csv")

df = pd.read_csv(csv_path, nrows=50000)

print("Dataset Loaded Successfully")
print("Shape:", df.shape)

df.head()

Dataset Loaded Successfully
Shape: (50000, 10)


,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...


In [5]:
light_reviews = df[df["Text"].str.contains("light", case=False, na=False)]

print("Number of reviews containing 'light':", len(light_reviews))

light_reviews[["Text"]].head(20)

Number of reviews containing 'light': 3511


,Text
2,This is a confection that has been around a fe...
5,I got a wild hair for taffy and ordered this f...
54,I roast at home with a stove-top popcorn poppe...
64,This product serves me well as a source of ele...
94,This is the same food we get at pet store. But...
101,Arrived slightly thawed. My parents wouldn't a...
178,"This is not as good as the Frozen Lemon juice,..."
189,The coffee is very finely processed and the fl...
221,I've tried a variety of Ahmad tea. Not because...
238,A very delicate green tea with a smooth light ...


In [6]:
sentences = [

"This olive oil is wonderful and very light on the stomach.",

"The packaging was broken and let too much light inside the box.",

"I prefer this snack because it is light and healthy."

]

In [7]:
print("Sentence 1:")
print(sentences[0])

print("\nSentence 2:")
print(sentences[1])

print("\nSentence 3:")
print(sentences[2])

Sentence 1:
This olive oil is wonderful and very light on the stomach.

Sentence 2:
The packaging was broken and let too much light inside the box.

Sentence 3:
I prefer this snack because it is light and healthy.


In [8]:
vectorizer = CountVectorizer()

document_term_matrix = vectorizer.fit_transform(sentences)

print("Vectorization Completed")

Vectorization Completed


In [9]:
dense_matrix = document_term_matrix.toarray()

print("Dense Matrix:\n")
print(dense_matrix)

Dense Matrix:

[[1 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


In [10]:
feature_names = vectorizer.get_feature_names_out()

print(feature_names)

['and' 'because' 'box' 'broken' 'healthy' 'inside' 'is' 'it' 'let' 'light'
 'much' 'oil' 'olive' 'on' 'packaging' 'prefer' 'snack' 'stomach' 'the'
 'this' 'too' 'very' 'was' 'wonderful']


In [11]:
vec_1 = dense_matrix[0]

vec_2 = dense_matrix[1]

vec_3 = dense_matrix[2]

print("Vector 1:")
print(vec_1)

print()

print("Vector 2:")
print(vec_2)

print()

print("Vector 3:")
print(vec_3)

Vector 1:
[1 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]

Vector 2:
[1 0 1 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]

Vector 3:
[1 1 0 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [12]:
similarity_1_2 = np.dot(vec_1, vec_2)

similarity_1_3 = np.dot(vec_1, vec_3)

In [13]:
print("="*50)

print("Dot Product Similarity")

print("="*50)

print()

print("Sentence 1 vs Sentence 2 (Different Context):")

print(similarity_1_2)

print()

print("Sentence 1 vs Sentence 3 (Similar Context):")

print(similarity_1_3)

Dot Product Similarity

Sentence 1 vs Sentence 2 (Different Context):
4

Sentence 1 vs Sentence 3 (Similar Context):
4


In [14]:
matrix_df = pd.DataFrame(
    dense_matrix,
    columns=feature_names,
    index=["Sentence 1","Sentence 2","Sentence 3"]
)

matrix_df

,and,because,box,broken,healthy,inside,is,it,let,light,...,packaging,prefer,snack,stomach,the,this,too,very,was,wonderful
Sentence 1,1,0,0,0,0,0,1,0,0,1,...,0,0,0,1,1,1,0,1,0,1
Sentence 2,1,0,1,1,0,1,0,0,1,1,...,1,0,0,0,2,0,1,0,1,0
Sentence 3,1,1,0,0,1,0,1,1,0,1,...,0,1,1,0,0,1,0,0,0,0


In [15]:
print("Conclusion")

if similarity_1_3 > similarity_1_2:
    print("Sentence 1 is mathematically more similar to Sentence 3.")
else:
    print("Sentence 1 is mathematically more similar to Sentence 2.")

print("\nBag-of-Words cannot understand the contextual meaning of words.")
print("It only counts word occurrences.")
print("Modern LLMs solve this problem using Context-Aware Embeddings and Self-Attention.")

Conclusion
Sentence 1 is mathematically more similar to Sentence 2.

Bag-of-Words cannot understand the contextual meaning of words.
It only counts word occurrences.
Modern LLMs solve this problem using Context-Aware Embeddings and Self-Attention.
