In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:

df = pd.read_csv("Reviews.csv", nrows=50000)

print("Dataset Shape:", df.shape)
print(df.columns)

Dataset Shape: (50000, 10)
Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')


In [3]:
# Filter reviews containing the word "light"
light_reviews = df[df["Text"].str.contains("light", case=False, na=False)]

print("Number of reviews containing 'light':", len(light_reviews))

# Display first 20 matching reviews
for i, review in enumerate(light_reviews["Text"].head(20)):
    print(f"\nReview {i+1}:")
    print(review)

Number of reviews containing 'light': 3511

Review 1:
This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.

Review 2:
I got a wild hair for taffy and ordered this five pound bag. The taffy was all very enjoyable with many flavors: watermelon, root beer, melon, peppermint, grape, etc. My only complaint is there was a bit too much red/black licorice-flavored pieces (just not my particular favorites). Between me, my kids, and my husband, this lasted only two weeks! I would recommend this brand of taffy -- it was a delightful treat.

Review 

In [4]:
sentences = [
    "This olive oil is wonderful and very light on the stomach.",
    "The packaging was broken and let too much light inside the box.",
    "I prefer this brand because it is a light and healthy snack."
]

print("Selected Sentences:")
for s in sentences:
    print("-", s)

Selected Sentences:
- This olive oil is wonderful and very light on the stomach.
- The packaging was broken and let too much light inside the box.
- I prefer this brand because it is a light and healthy snack.


In [5]:
vectorizer = CountVectorizer()

matrix = vectorizer.fit_transform(sentences)

dense_matrix = matrix.toarray()

print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nDense Matrix:")
print(dense_matrix)

Vocabulary:
['and' 'because' 'box' 'brand' 'broken' 'healthy' 'inside' 'is' 'it' 'let'
 'light' 'much' 'oil' 'olive' 'on' 'packaging' 'prefer' 'snack' 'stomach'
 'the' 'this' 'too' 'very' 'was' 'wonderful']

Dense Matrix:
[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


In [6]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print("Vector 1:", vec_1)
print("Vector 2:", vec_2)
print("Vector 3:", vec_3)

Vector 1: [1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
Vector 2: [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
Vector 3: [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [7]:
similarity_1_2 = np.dot(vec_1, vec_2)

similarity_1_3 = np.dot(vec_1, vec_3)

print("\nSimilarity Scores")
print("------------------")
print("Sentence 1 vs Sentence 2:", similarity_1_2)
print("Sentence 1 vs Sentence 3:", similarity_1_3)


Similarity Scores
------------------
Sentence 1 vs Sentence 2: 4
Sentence 1 vs Sentence 3: 4


In [8]:
print("\nConclusion:")
print("CountVectorizer treats words as counts.")
print("It cannot understand that the word 'light' has different meanings in different contexts.")
print("This demonstrates the limitation of Bag-of-Words representations.")


Conclusion:
CountVectorizer treats words as counts.
It cannot understand that the word 'light' has different meanings in different contexts.
This demonstrates the limitation of Bag-of-Words representations.
